ADOODLEYDO_DB_DJANGO_USER_PWD=""
DJANGO_SECRET_KEY="django-insecure-2)cv(==vw8j8704#9nq)0qedwmcevj1faa9*86^m4aop-cphoe"
DJANGO_DEBUG=true
SESSION_COOKIE_SECURE=false
CSRF_COOKIE_SECURE=false
SECURE_SSL_REDIRECT=false
SECURE_HSTS_SECONDS=false
DB_HOST="localhost"
ALLOWED_HOSTS=["127.0.0.1"]